/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { ResponseCreateNestedManyWithoutEmployeesInput } from "./ResponseCreateNestedManyWithoutEmployeesInput";
import { Type } from "class-transformer";
import { DepartmentWhereUniqueInput } from "../../department/base/DepartmentWhereUniqueInput";
import { ReminderCreateNestedManyWithoutEmployeesInput } from "./ReminderCreateNestedManyWithoutEmployeesInput";

@InputType()
class EmployeeCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => ResponseCreateNestedManyWithoutEmployeesInput,
  })
  @ValidateNested()
  @Type(() => ResponseCreateNestedManyWithoutEmployeesInput)
  @IsOptional()
  @Field(() => ResponseCreateNestedManyWithoutEmployeesInput, {
    nullable: true,
  })
  responses?: ResponseCreateNestedManyWithoutEmployeesInput;

  @ApiProperty({
    required: false,
    type: () => DepartmentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DepartmentWhereUniqueInput)
  @IsOptional()
  @Field(() => DepartmentWhereUniqueInput, {
    nullable: true,
  })
  department?: DepartmentWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ReminderCreateNestedManyWithoutEmployeesInput,
  })
  @ValidateNested()
  @Type(() => ReminderCreateNestedManyWithoutEmployeesInput)
  @IsOptional()
  @Field(() => ReminderCreateNestedManyWithoutEmployeesInput, {
    nullable: true,
  })
  reminders?: ReminderCreateNestedManyWithoutEmployeesInput;
}

export { EmployeeCreateInput as EmployeeCreateInput };
