/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { EnumSurveyFrequency } from "./EnumSurveyFrequency";
import { QuestionListRelationFilter } from "../../question/base/QuestionListRelationFilter";
import { ResponseListRelationFilter } from "../../response/base/ResponseListRelationFilter";

@InputType()
class SurveyWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  title?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumSurveyFrequency,
  })
  @IsEnum(EnumSurveyFrequency)
  @IsOptional()
  @Field(() => EnumSurveyFrequency, {
    nullable: true,
  })
  frequency?: "Option1";

  @ApiProperty({
    required: false,
    type: () => QuestionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => QuestionListRelationFilter)
  @IsOptional()
  @Field(() => QuestionListRelationFilter, {
    nullable: true,
  })
  questions?: QuestionListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ResponseListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ResponseListRelationFilter)
  @IsOptional()
  @Field(() => ResponseListRelationFilter, {
    nullable: true,
  })
  responses?: ResponseListRelationFilter;
}

export { SurveyWhereInput as SurveyWhereInput };
